name: Generate RCENet library (staging)

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build_rcenet:
    defaults:
      run:
        shell: ${{ matrix.config.platform == 'mingw' && 'msys2 {0}' || 'bash' }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { runner: ubuntu-latest,  platform: bsd,                                 arch: x86_64, kind: shared }
        - { runner: ubuntu-latest,  platform: bsd,                                 arch: x86_64, kind: static }
        - { runner: ubuntu-latest,  platform: bsd,                                 arch: i386, kind: shared }
        - { runner: ubuntu-latest,  platform: bsd,                                 arch: i386, kind: static }
        - { runner: windows-latest, platform: windows,                             arch: x86, kind: shared }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: x86, kind: static }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: x64, kind: shared }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: x64, kind: static }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm, kind: shared }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm, kind: static }     # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm64, kind: shared }   # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm64, kind: static }   # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm64ec, kind: shared } # Windows MSVC
        - { runner: windows-latest, platform: windows,                             arch: arm64ec, kind: static } # Windows MSVC
        - { runner: windows-latest, platform: mingw,                               arch: i386, msys_arch: i686, msys_msystem: mingw32, kind: static }     # Windows MinGW
        - { runner: windows-latest, platform: mingw,                               arch: x86_64, msys_arch: x86_64, msys_msystem: mingw64, kind: static } # Windows MinGW
        - { runner: ubuntu-latest,  platform: linux,                               arch: i386, kind: shared }
        - { runner: ubuntu-latest,  platform: linux,                               arch: i386, kind: static }
        - { runner: ubuntu-latest,  platform: linux,                               arch: x86_64, kind: shared }
        - { runner: ubuntu-latest,  platform: linux,                               arch: x86_64, kind: static }
        - { runner: ubuntu-latest,  platform: linux,                               arch: arm, kind: shared }
        - { runner: ubuntu-latest,  platform: linux,                               arch: arm, kind: static }
        - { runner: ubuntu-latest,  platform: linux,                               arch: arm64, kind: shared }
        - { runner: ubuntu-latest,  platform: linux,                               arch: arm64, kind: static }
        - { runner: ubuntu-latest,  platform: haiku,                               arch: i386, kind: shared }
        - { runner: ubuntu-latest,  platform: haiku,                               arch: i386, kind: static }
        - { runner: ubuntu-latest,  platform: haiku,                               arch: x86_64, kind: shared }
        - { runner: ubuntu-latest,  platform: haiku,                               arch: x86_64, kind: static }
        - { runner: ubuntu-latest,  platform: android,                             arch: x86, kind: shared }
        - { runner: ubuntu-latest,  platform: android,                             arch: x86, kind: static }
        - { runner: ubuntu-latest,  platform: android,                             arch: x86_64, kind: shared }
        - { runner: ubuntu-latest,  platform: android,                             arch: x86_64, kind: static }
        - { runner: ubuntu-latest,  platform: android,                             arch: armeabi-v7a, kind: shared }
        - { runner: ubuntu-latest,  platform: android,                             arch: armeabi-v7a, kind: static  }
        - { runner: ubuntu-latest,  platform: android,                             arch: arm64-v8a, kind: shared }
        - { runner: ubuntu-latest,  platform: android,                             arch: arm64-v8a, kind: static }
        - { runner: macos-14,       platform: macos,         sdk: macosx,          arch: "x86_64,arm64", kind: shared }
        - { runner: macos-14,       platform: macos,         sdk: macosx,          arch: "x86_64,arm64", kind: static }
        - { runner: macos-14,       platform: ios,           sdk: iphoneos,        arch: "arm64,arm64e", kind: static }
        - { runner: macos-14,       platform: ios,           sdk: iphonesimulator, arch: "x86_64,arm64", kind: static }
        - { runner: macos-14,       platform: appletvos,     sdk: appletvos,       arch: "armv7,arm64,i386,x86_64", kind: static }
        - { runner: macos-14,       platform: applexros,     sdk: xros,            arch: "arm64,x86_64", kind: static }
        mode: [debug]  # Rajouter : release (si besoin)
    name: ${{ matrix.config.platform }}-${{ matrix.config.arch }}-${{ matrix.config.sdk }}-${{ matrix.mode }}-${{ matrix.config.kind }}
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies i386 - Linux / BSD / Haiku
        if: ${{ matrix.config.arch == 'i386' && (matrix.config.platform == 'linux' || matrix.config.platform == 'bsd' || matrix.config.platform == 'haiku') }}
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      - name: Setup MSys2 - MinGW
        if: ${{ matrix.config.platform == 'mingw' }}
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msys_msystem }}
          install: >-
            base-devel 
            git 
            unzip 
            p7zip 
            mingw-w64-${{ matrix.config.msys_arch }}-toolchain 
            mingw-w64-${{ matrix.config.msys_arch }}-xmake
          update: true

      - name: Setup new version xCode and Setup Command Line Tools - macOS / iOS
        # Doc : https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
        if: matrix.config.runner == 'macos-14'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4.0'

      - name: Determine SDK Path and set SDKROOT - macOS / iOS
        if: matrix.config.runner == 'macos-14'
        run: |
          sdk="${{ matrix.config.sdk }}"
          SDKROOT=$(xcrun --sdk $sdk --show-sdk-path)
          echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV
          echo "Using SDK: $sdk"

      - name: Setup NDK latest LTS - Android
        if: ${{ matrix.config.platform == 'android' }}
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
          link-to-sdk: true
          add-to-path: true

      - name: Setup xMake - All platforms (except MinGW)
        # This action also works with MinGW but is slower (compiles from source)
        if: ${{ matrix.config.platform != 'mingw' }}
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Configure project with xMake - Windows-MSVC / Linux / BSD / Haiku
        if: ${{ matrix.config.platform == 'windows' || matrix.config.platform == 'linux' || matrix.config.platform == 'bsd' || matrix.config.platform == 'haiku' }}
        run: xmake config --plat=${{ matrix.config.platform }} --arch=${{ matrix.config.arch }} --mode=${{ matrix.mode }} --kind=${{ matrix.config.kind }} --yes

      - name: Configure project with xMake - Android
        if: ${{ matrix.config.platform == 'android' }}
        run:
          # --ndk_sdkver = SDK / API level Android minimal used
          # Informations : Pour éviter de construire 2 fois pour l'architecture : armeabi-v7a si on construit 
          # à partir de l'API/SDK 23 d'Android ça sera compatible pour NEON et SANS NEON
          xmake config --ndk=${{ steps.setup-ndk.outputs.ndk-path }} --ndk_sdkver=23 --plat=${{ matrix.config.platform }} --arch=${{ matrix.config.arch }} --mode=${{ matrix.mode }} --kind=${{ matrix.config.kind }} --yes

      - name: Configure project with xMake - macOS / tvOS / xrOS
        if: ${{ matrix.config.sdk == 'macosx' || matrix.config.sdk == 'appletvos' || matrix.config.sdk == 'applexros' }}
        run: xmake m package --plat=${{ matrix.config.sdk }} --arch=${{ matrix.config.arch }} -f "--target_minver=11.0 --mode=${{ matrix.mode }} --kind=${{ matrix.config.kind }} --yes"

      - name: Configure project with xMake - iOS (iphoneos)
        if: ${{ matrix.config.sdk == 'iphoneos' }}
        # Pas de library shared pour iOS (.dylib) suite au restrictions d'Apple, utiliser .framework, .xcframework ou .a
        run: xmake m package --plat=${{ matrix.config.sdk }} --arch=${{ matrix.config.arch }} -f "--target_minver=12.0 --mode=${{ matrix.mode }} --kind=${{ matrix.config.kind }} --yes"

      - name: Configure project with xMake - iOS (iphonesimulator)
        if: ${{ matrix.config.sdk == 'iphonesimulator' }}
        # Pas de library shared pour iOS (.dylib) suite au restrictions d'Apple, utiliser .framework, .xcframework ou .a
        run: xmake m package --plat=iphoneos --arch=${{ matrix.config.arch }} -f "--appledev=simulator --target_minver=12.0 --mode=${{ matrix.mode }} --kind=${{ matrix.config.kind }} --yes"

      - name: Build project with xMake
        run: xmake

      - name: Install project with xMake
        # v = verbose, o = output directory
        run: | 
          xmake install -v -o rcenet/
          ls -l -R rcenet/

      - name: Create fatlib universal (dynamic) - macOS
        if: ${{ matrix.config.sdk == 'macosx' }}
        run: |
          mkdir -p rcenet/x86_64-arm64/${{ matrix.config.kind }}
          lipo -create rcenet/x86_64/${{ matrix.config.kind }}/librcenet.dylib rcenet/arm64/${{ matrix.config.kind }}/librcenet.dylib -output rcenet/x86_64-arm64/${{ matrix.config.kind }}/librcenet.dylib
          rm -rf rcenet/x86_64 rcenet/arm64

      - name: Create fatlib universal (static) - macOS
        if: ${{ matrix.config.sdk == 'macosx' }}
        run: |
          mkdir -p rcenet/x86_64-arm64/${{ matrix.config.kind }}
          lipo -create rcenet/x86_64/${{ matrix.config.kind }}/librcenet.a rcenet/arm64/${{ matrix.config.kind }}/librcenet.a -output rcenet/x86_64-arm64/${{ matrix.config.kind }}/librcenet.a
          rm -rf rcenet/x86_64 rcenet/arm64

      - name: Create fatlib universal - iOS (iphoneos)
        if: ${{ matrix.config.sdk == 'iphoneos' }}
        run: |
          mkdir -p rcenet/arm64-arm64e/${{ matrix.config.kind }}
          lipo -create rcenet/arm64/${{ matrix.config.kind }}/librcenet.a rcenet/arm64e/${{ matrix.config.kind }}/librcenet.a -output rcenet/arm64-arm64e/${{ matrix.config.kind }}/librcenet.a
          rm -rf rcenet/arm64 rcenet/arm64e

      - name: Create fatlib universal - iOS (iphonesimulator)
        if: ${{ matrix.config.sdk == 'iphonesimulator' }}
        run: |
          mkdir -p rcenet/x86_64-arm64/${{ matrix.config.kind }}
          lipo -create rcenet/x86_64/${{ matrix.config.kind }}/librcenet.a rcenet/arm64/${{ matrix.config.kind }}/librcenet.a -output rcenet/x86_64-arm64/${{ matrix.config.kind }}/librcenet.a
          rm -rf rcenet/x86_64 rcenet/arm64

      - name: Upload artifacts Binary RCENet
        uses: actions/upload-artifact@v4
        with:
          name: librcenet-${{ matrix.config.platform }}-${{ matrix.config.arch }}-${{ matrix.config.sdk }}-${{ matrix.mode }}-${{ matrix.config.kind }}
          path: rcenet/
          retention-days: 1

  build_deploy_website:
    needs: build_rcenet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js latest LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build with VitePress
        run: npm run build
        working-directory: ./docs

      - name: Deploy files website static for docs API RCENet
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.O2SWITCH_FTP_HOST }}
          username: ${{ secrets.O2SWITCH_FTP_USERNAME }}
          password: ${{ secrets.O2SWITCH_FTP_PASSWORD }}
          port: ${{ secrets.O2SWITCH_FTP_PORT }}
          protocol: ftp
          local-dir: ./docs/.vitepress/dist/
          server-dir: staging.librcenet.crzcommon2.com/
          exclude: |
            dist